param(
    [Parameter(Mandatory)]
    [string] $OutputPath,
    [string] $BaseRef = 'HEAD'
)

$ErrorActionPreference = 'Stop'

function Get-PackageVersions([xml] $Document) {
    $versions = @{}
    foreach ($node in $Document.SelectNodes("//*[local-name()='PackageReference' or local-name()='PackageVersion']")) {
        $id = $node.GetAttribute('Include')
        if (-not $id) { $id = $node.GetAttribute('Update') }
        $version = $node.GetAttribute('VersionOverride')
        if (-not $version) { $version = $node.GetAttribute('Version') }
        if (-not $version) {
            $child = $node.SelectSingleNode("*[local-name()='VersionOverride' or local-name()='Version']")
            if ($child) { $version = $child.InnerText }
        }
        if (-not $id -or -not $version) { continue }

        # Keep conditional references distinct when a project declares a package twice.
        $conditions = @($node.SelectNodes('ancestor-or-self::*[@Condition]') | ForEach-Object { $_.GetAttribute('Condition') })
        $key = @($node.LocalName, $id) + $conditions | ConvertTo-Json -Compress
        $versions[$key] = [pscustomobject]@{ Id = $id; Version = $version }
    }
    return $versions
}

function Format-Cell([string] $Value) {
    return [System.Net.WebUtility]::HtmlEncode($Value).Replace('|', '&#124;').Replace('`', '&#96;').Replace("`r", '').Replace("`n", ' ')
}

$files = @(git diff --name-only --diff-filter=M $BaseRef -- 'src/Avalonia.Samples/*.csproj' 'src/Avalonia.Samples/*.fsproj' 'src/Avalonia.Samples/*.props')
if ($LASTEXITCODE -ne 0) { throw 'Could not list changed dependency files.' }

$updates = @{}
foreach ($file in $files) {
    $original = git show "${BaseRef}:$file" | Out-String
    if ($LASTEXITCODE -ne 0) { throw "Could not read the original version of $file." }
    # Native stdout preserves a UTF-8 BOM as U+FEFF; XML string parsing rejects it.
    $original = $original.TrimStart([char] 0xFEFF)
    $before = Get-PackageVersions ([xml] $original)
    $after = Get-PackageVersions ([xml] (Get-Content -LiteralPath $file -Raw))
    foreach ($key in $after.Keys) {
        if (-not $before.ContainsKey($key) -or $before[$key].Version -eq $after[$key].Version) { continue }
        $package = $after[$key].Id
        $oldVersion = $before[$key].Version
        $newVersion = $after[$key].Version
        $group = @($package, $oldVersion, $newVersion) | ConvertTo-Json -Compress
        if (-not $updates.ContainsKey($group)) {
            $updates[$group] = [pscustomobject]@{
                Package = $package
                From = $oldVersion
                To = $newVersion
                Files = [System.Collections.Generic.List[string]]::new()
            }
        }
        if (-not $updates[$group].Files.Contains($file)) { $updates[$group].Files.Add($file) }
    }
}

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('Updates NuGet dependencies within their current major versions. Major upgrades are handled separately through tracking issues.')
$lines.Add('')
$lines.Add('## Package changes')
$lines.Add('')
if ($updates.Count -gt 0) {
    $lines.Add('| Package | From | To | Projects / central package files |')
    $lines.Add('| --- | --- | --- | --- |')
    foreach ($update in ($updates.Values | Sort-Object Package, From, To)) {
        $paths = ($update.Files | Sort-Object | ForEach-Object { '<code>{0}</code>' -f (Format-Cell $_) }) -join '<br>'
        $lines.Add(('| {0} | {1} | {2} | {3} |' -f (Format-Cell $update.Package), (Format-Cell $update.From), (Format-Cell $update.To), $paths))
    }
} else {
    $lines.Add('No explicit package version changes were found in project or central package files. Review the diff for other changes before merging.')
}
$lines.Add('')
$lines.Add('## Validation')
$lines.Add('')
$lines.Add('- Package restore completed for all sample projects after the updates.')
$lines.Add('- Builds and tests are not run by this workflow.')
$lines.Add('')
$lines.Add('## Review')
$lines.Add('')
$lines.Add('- [ ] Check release notes for the updated packages.')
$lines.Add('- [ ] Verify builds and tests, including affected Desktop, Android, iOS, and Browser targets.')
$lines.Add('- [ ] Smoke-test the affected samples for behavior changes.')
if ($env:GITHUB_SERVER_URL -and $env:GITHUB_REPOSITORY -and $env:GITHUB_RUN_ID) {
    $lines.Add('')
    $lines.Add("Generated by the [Update dependencies workflow]($env:GITHUB_SERVER_URL/$env:GITHUB_REPOSITORY/actions/runs/$env:GITHUB_RUN_ID).")
}
Set-Content -LiteralPath $OutputPath -Value $lines -Encoding utf8
