= MVVM Dialog Sample
// --- D O N ' T    T O U C H   T H I S    S E C T I O N ---
:toc:
:toc-placement!:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
// ----------------------------------------------------------



// Write a short summary here what this examples does
This example will show you how to use `Interactions` to show https://docs.avaloniaui.net/docs/next/basics/user-interface/file-dialogs[[dialogs\]] in your MVVM application



// --- D O N ' T    T O U C H   T H I S    S E C T I O N ---
toc::[]
// ---------------------------------------------------------


=== Difficulty
// Choose one of the below difficulties. You can just delete the ones you don't need.

🐔 Normal 🐔



=== Buzz-Words

// Write some buzz-words here. You can separate them by ", "
MVVM, Dialog, FileDialogs, TopLevel, Clipboard



== Before we start

We assume you already now how the MVVM pattern works and how dialogs, such as file dialogs, can be shown in general. You should also know what a https://docs.avaloniaui.net/docs/next/concepts/toplevel[[TopLevel\]]-control in Avalonia is and what it can be used for. 


== Solution 1 : Use ReactiveUI-Interactions

In this section you will learn how to use Reactive UI https://www.reactiveui.net/docs/handbook/interactions/[[`Interactions`\]] in order to interact with your `View`.

=== Step 1: Setup the ViewModel 

In our ViewModel we add a property for the `Interaction` which we can use later to interact with the `View`, for example inside a `Command`:

[source,c#]
----
public InteractionViewModel()
{
    _SelectFilesInteraction = new Interaction<string?, string[]?>();
}

private readonly Interaction<string?, string[]?> _selectFilesInteraction;

/// <summary>
/// Gets the select files interaction
/// </summary>
public Interaction<string?, string[]?> SelectFilesInteraction => this.selectFilesInteraction;
----

The `Interaction` is a generic class, where the first parameter defines the input (in our case the file dialog title) and the second parameter defines the expected return type (in our case a list of files).


=== Step 2: Prepare the View

We add a `ReactiveUserControl` as your view. This control gives us the ability to register a handler for our interactions. Let's add this handler in the UserControls code behind:

[source,cs]
----
private async Task InteractionHandler(InteractionContext<string?, string[]?> context)
{
    // Get our parent top level control in order to get the needed service (in our sample the storage provider. Can also be the clipboard etc.)
    var topLevel = TopLevel.GetTopLevel(this);

    var storageFiles = await topLevel!.StorageProvider
        .OpenFilePickerAsync(
                    new FilePickerOpenOptions()
                    {
                        AllowMultiple = true,
                        Title = context.Input
                    });
       
    context.SetOutput(storageFiles?.Select(x => x.Name).ToArray());
}
---- 

NOTE: We are using an async Task to not block the UI. As parameter we need to pass an `InteractionContext` which has one generic parameter for the input (in our case a string for the dialog title) and one for the output (in our case an array of selected filed). 

In the constructor of our `ReactiveUserControl` we need to setup the interaction inside `this.WhenActivated` like shown below: 

[source,C#]
----
public InteractionView()
{
    InitializeComponent();

    this.WhenActivated(d =>
    {
        d(ViewModel.SelectFilesInteraction.RegisterHandler(this.InteractionHandler));
    });
}
----

Now we can setup the `XAML` as following. Mind the binding of the `Button` to our `Command` in the `ViewModel`:

[source,xml]
----
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:vm="using:MvvmDialogSample.ViewModels"
			 mc:Ignorable="d" d:DesignWidth="800" d:DesignHeight="450"
             x:DataType="vm:InteractionViewModel"
			 x:Class="MvvmDialogSample.Views.InteractionView">
	<Grid RowDefinitions="Auto,*,Auto">
		<TextBlock Text="Selected Files:" />
		<ListBox ItemsSource="{Binding SelectedFiles}" Grid.Row="1" />
		<Button Content="Select Files"
				Command="{Binding SelectFilesCommand}"
				Grid.Row="2" />
	</Grid>
</UserControl>
----

=== Step 3: See it in action

Running the App you should be able to select any files on your system. 


== Related 

There are more ways to show dialogs from the ViewModel, for example: 
  
* link:../AdvancedMvvmDialogSample[Dialog Service]
* https://github.com/AvaloniaCommunity/awesome-avalonia#mvvm--mvp--mvu[third party libs]
// Any related information or further readings goes here.



// --------------- Ascii-Doc Cheat-Sheet ------------------

// visit: https://asciidoc.org 
// visit: https://powerman.name/doc/asciidoc-compact

// VS-Code has a great Add-In for Ascii docs: https://github.com/asciidoctor/asciidoctor-vscode/